=== PabVF23/EscritorioVirtual/xml/rutas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.pabvf.es/rutas"
xmlns="http://www.pabvf.es/rutas"
elementFormDefault="qualified">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fecha" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="hora" type="xs:time" minOccurs="0" maxOccurs="1" />
				<xs:element name="tiempo" type="xs:duration"/>
				<xs:element name="agencia" type="xs:string" />
				<xs:element name="descripcion" type="xs:string" />
				<xs:element name="personas" type="xs:string" />
				<xs:element name="lugar" type="xs:string" />
				<xs:element name="direccion" type="xs:string" />
				<xs:element ref="coordenadas" />
				<xs:element ref="referencias" />
				<xs:element ref="recomendacion" />
				<xs:element ref="hitos" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tipo" type="xs:string" use="required" />
			<xs:attribute name="medio" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:attribute name="longitud" type="xs:float" use="required" />
			<xs:attribute name="latitud" type="xs:float" use="required" />
			<xs:attribute name="altitud" type="xs:float" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="referencia" type="xs:string" minOccurs="3" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0" />
				<xs:maxInclusive value="10" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hito" minOccurs="3" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="descripcion" type="xs:string" />
				<xs:element ref="coordenadas" />
				<xs:element name="distancia">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="unidades" type="xs:string" use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="galeriaFotos">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="foto" type="xs:string" minOccurs="1" maxOccurs="5"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="galeriaVideos" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="video" type="xs:string" minOccurs="1" maxOccurs="3"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== PabVF23/EscritorioVirtual/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es rutas.xsd" >
    <ruta nombre="Ruta por Nuku'Alofa" tipo="Senderismo" medio="A pie">
        <fecha>2023-12-15</fecha>
        <hora>12:00:00</hora>
        <tiempo>PT6H</tiempo>
        <agencia>RutasTonga</agencia>
        <descripcion>Se visitarán los lugares más destacados de la capital de la isla</descripcion>
        <personas>Se puede ir con niños</personas>
        <lugar>Palacio Real de Tonga</lugar>
        <direccion>VQ9X+FQ2, Vuna Rd, Nuku'alofa, Tonga</direccion>
        <coordenadas latitud="-21.13117063262022" longitud="-175.2005886457105" altitud="1"/>
        <referencias>
            <referencia>
                https://es.wikipedia.org/wiki/Nukualofa
            </referencia>
            <referencia>
                https://es.wikipedia.org/wiki/Palacio_Real_de_Tonga
            </referencia>
            <referencia>
                https://www.royalpalace.to/
            </referencia>
        </referencias>
        <recomendacion>7</recomendacion>
        <hitos>
            <hito nombre="Palacio Real de Tonga">
                <descripcion>Residencia de Tupou VI, Rey de Tonga</descripcion>
                <coordenadas latitud="-21.13117063262022" longitud="-175.2005886457105" altitud="1"/>
                <distancia unidades="m">0</distancia>
                <galeriaFotos>
                    <foto>palacio.png</foto>
                </galeriaFotos>
            </hito>
            <hito nombre="Telekava European Cemetery">
                <descripcion>Cementerio a los caidos en la Segunda Guerra Mundial</descripcion>
                <coordenadas latitud="-21.13421725022125" longitud="-175.20945121535524" altitud="1"/>
                <distancia unidades="m">963.99</distancia>
                <galeriaFotos>
                    <foto>cementerio.png</foto>
                </galeriaFotos>
            </hito>
            <hito nombre="Tonga National Museum">
                <descripcion>Museo nacional de Tonga</descripcion>
                <coordenadas latitud="-21.13844583593113" longitud="-175.20396822904885" altitud="1"/>
                <distancia unidades="m">733.22</distancia>
                <galeriaFotos>
                    <foto>museo.png</foto>
                </galeriaFotos>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Visita Playa Ha'atafu" tipo="Paisajística" medio="En bici">
        <fecha>2023-12-13</fecha>
        <hora>10:00:00</hora>
        <tiempo>PT16H</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcion>Un viaje en bici para visitar la playa de Ha'atafu, con la posibilidad de bañarse en ella</descripcion>
        <personas>Personas en buena forma física</personas>
        <lugar>ANT Bicycles Tonga</lugar>
        <direccion>Railway Rd, Nuku'alofa, Tonga</direccion>
        <coordenadas latitud="-21.13718666160756" longitud="-175.20163424666714" altitud="1"/>
        <referencias>
            <referencia>
                https://www.tripadvisor.es/Attraction_Review-g317040-d315301-Reviews-Ha_atafu_Beach-Tongatapu_Island.html
            </referencia>
            <referencia>
                https://www.surfingtonga.com/index.html
            </referencia>
            <referencia>
                https://www.lonelyplanet.es/oceania/tonga/imprescindible/playa-de-haatafu
            </referencia>
        </referencias>
        <recomendacion>6</recomendacion>
        <hitos>
            <hito nombre="Coco de 3 cabezas">
                <descripcion>Una atracción turística muy visitada, un arbol de cocos con 3 cabezas</descripcion>
                <coordenadas latitud="-21.157854674108894" longitud="-175.27755641907672" altitud="1"/>
                <distancia unidades="m">0</distancia>
                <galeriaFotos>
                    <foto>coco.jpg</foto>
                    <foto>coco.png</foto>
                    <foto>coco.svg</foto>
                    <foto>coco2.jpg</foto>
                    <foto>coco2.png</foto>
                </galeriaFotos>
            </hito>
            <hito nombre="Heilala Holiday Lodge">
                <descripcion>Resort vacacional de Heilala</descripcion>
                <coordenadas latitud="-21.07158149791907" longitud="-175.33522905520314" altitud="1"/>
                <distancia unidades="m">733.22</distancia>
                <galeriaFotos>
                    <foto>cementerio.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>cementerio.mp4</video>
                </galeriaVideos>
            </hito>
            <hito nombre="Playa de Ha'atafu">
                <descripcion>Playa protegida para nadar y hacer surf</descripcion>
                <coordenadas latitud="-21.06976568669056" longitud="-175.3349976690178" altitud="1"/>
                <distancia unidades="m">963.99</distancia>
                <galeriaFotos>
                    <foto>playa.png</foto>
                    <foto>playa2.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>cementerio.mp4</video>
                    <video>cementerio.mkv</video>
                    <video>cementerio.avi</video>
                </galeriaVideos>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Visita a las islas" tipo="Senderismo" medio="A pie (con trayectos en barco entre las islas)">
        <fecha>2023-12-19</fecha>
        <hora>20:00:00</hora>
        <tiempo>PT20H</tiempo>
        <agencia>Nukunukumotu Tours</agencia>
        <descripcion>Una visita guiada a algunas de las distintas islas que conforman Tonga</descripcion>
        <personas>Se pueden llevar niños</personas>
        <lugar>Palacio Real de Tonga</lugar>
        <direccion>VQ9X+FQ2, Vuna Rd, Nuku'alofa, Tonga</direccion>
        <coordenadas latitud="-21.13117063262022" longitud="-175.2005886457105" altitud="1"/>
        <referencias>
            <referencia>
                https://to.geoview.info/nukunukumotu_island,4032391
            </referencia>
            <referencia>
                https://en.wikipedia.org/wiki/Pangaimotu_(Vava%CA%BBu)
            </referencia>
            <referencia>
                https://mapcarta.com/20410440
            </referencia>
        </referencias>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito nombre="Isla de Nukunukumotu">
                <descripcion>Isla localizada a una corta distancia al este de Nukualofa</descripcion>
                <coordenadas latitud="-21.14200661114548" longitud="-175.1460399023326" altitud="7"/>
                <distancia unidades="m">0</distancia>
                <galeriaFotos>
                    <foto>isla.jpg</foto>
                    <foto>isla.png</foto>
                </galeriaFotos>
            </hito>
            <hito nombre="Isla de Oneata">
                <descripcion>Isla localizada al norte de Nukunukumotu</descripcion>
                <coordenadas latitud="-21.129241417647656" longitud="-175.14618839323603" altitud="7"/>
                <distancia unidades="km">1.46</distancia>
                <galeriaFotos>
                    <foto>oneata.png</foto>
                    <foto>oneata2.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>oneata.mp4</video>
                </galeriaVideos>
            </hito>
            <hito nombre="Isla de Pangaimotu">
                <descripcion>Isla localizada al noroeste de Oneata</descripcion>
                <coordenadas latitud="-21.124028934272" longitud="-175.1590628165866" altitud="7"/>
                <distancia unidades="km">1.40</distancia>
                <galeriaFotos>
                    <foto>pangaimotu.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>pangaimotu.mp4</video>
                    <video>pangaimotu2.avi</video>
                </galeriaVideos>
            </hito>
        </hitos>
    </ruta>
</rutas>
