=== PabVF23/EscritorioVirtual/xml/rutas.dtd
<!-- Declaraciones de elementos -->
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (fecha?, hora?, tiempo, agencia, descripcion,
                personas, lugar, direccion, coordenadas,
                referencias,
                recomendacion, hitos)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT personas (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT coordenadas EMPTY>
<!ELEMENT referencias (referencia, referencia, referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion EMPTY>
<!ELEMENT hitos (hito, hito, hito+)>

<!ELEMENT hito (descripcion, coordenadas, distancia, galeriaFotos, galeriaVideos?)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT galeriaFotos (foto, foto?, foto?, foto?, foto?)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT galeriaVideos (video, video?, video?)>
<!ELEMENT video (#PCDATA)>

<!-- Declaraciones de atributos -->
<!ATTLIST ruta
            nombre CDATA #REQUIRED
            tipo CDATA #REQUIRED
            medio CDATA #REQUIRED>
            
<!ATTLIST coordenadas
            longitud CDATA #REQUIRED
            latitud CDATA #REQUIRED
            altitud CDATA #REQUIRED>

<!ATTLIST recomendacion
            valor (0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10) #REQUIRED>

<!ATTLIST hito
            nombre CDATA #REQUIRED>

<!ATTLIST distancia
            unidades CDATA #REQUIRED>

=== PabVF23/EscritorioVirtual/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">

<rutas>
    <ruta nombre="Ruta por Nuku'Alofa" tipo="Senderismo" medio="A pie">
        <fecha>15-12-2023</fecha>
        <hora>12:00</hora>
        <tiempo>6 horas</tiempo>
        <agencia>RutasTonga</agencia>
        <descripcion>Se visitarán los lugares más destacados de la capital de la isla</descripcion>
        <personas>Se puede ir con niños</personas>
        <lugar>Palacio Real de Tonga</lugar>
        <direccion>VQ9X+FQ2, Vuna Rd, Nuku'alofa, Tonga</direccion>
        <coordenadas latitud="-175.2005886457105" longitud="-21.13117063262022" altitud="1"/>
        <referencias>
            <referencia>
                https://es.wikipedia.org/wiki/Nukualofa
            </referencia>
            <referencia>
                https://es.wikipedia.org/wiki/Palacio_Real_de_Tonga
            </referencia>
            <referencia>
                https://www.royalpalace.to/
            </referencia>
        </referencias>
        <recomendacion valor="7"/>
        <hitos>
            <hito nombre="Palacio Real de Tonga">
                <descripcion>Residencia de Tupou VI, Rey de Tonga</descripcion>
                <coordenadas latitud="-175.2005886457105" longitud="-21.13117063262022" altitud="1"/>
                <distancia unidades="m">0</distancia>
                <galeriaFotos>
                    <foto>palacio.jpg</foto>
                </galeriaFotos>
            </hito>
            <hito nombre="Telekava Cemetery">
                <descripcion>Cementerio a los caidos en la Segunda Guerra Mundial</descripcion>
                <coordenadas latitud="-175.20945121535524" longitud="-21.13421725022125" altitud="1"/>
                <distancia unidades="m">963.99</distancia>
                <galeriaFotos>
                    <foto>cementerio.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>cementerio.mp4</video>
                </galeriaVideos>
            </hito>
            <hito nombre="Tonga National Museum">
                <descripcion>Museo nacional de Tonga</descripcion>
                <coordenadas latitud="-175.20396822904885" longitud="-21.13844583593113" altitud="1"/>
                <distancia unidades="m">733.22</distancia>
                <galeriaFotos>
                    <foto>cementerio.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>cementerio.mp4</video>
                </galeriaVideos>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Visita Playa Ha'atafu" tipo="Paisajística" medio="En bici">
        <fecha>13-12-2023</fecha>
        <hora>10:00</hora>
        <tiempo>16 horas</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcion>Un viaje en bici para visitar la playa de Ha'atafu, con la posibilidad de bañarse en ella</descripcion>
        <personas>Personas en buena forma física</personas>
        <lugar>ANT Bicycles Tonga</lugar>
        <direccion>Railway Rd, Nuku'alofa, Tonga</direccion>
        <coordenadas latitud="-175.20163424666714" longitud="-21.13718666160756" altitud="1"/>
        <referencias>
            <referencia>
                https://www.tripadvisor.es/Attraction_Review-g317040-d315301-Reviews-Ha_atafu_Beach-Tongatapu_Island.html
            </referencia>
            <referencia>
                https://www.surfingtonga.com/index.html
            </referencia>
            <referencia>
                https://www.lonelyplanet.es/oceania/tonga/imprescindible/playa-de-haatafu
            </referencia>
        </referencias>
        <recomendacion valor="10"/>
        <hitos>
            <hito nombre="Ha'atafu Beach Resort">
                <descripcion>Resort cerca de la playa de Ha'atafu (actualmente cerrado)</descripcion>
                <coordenadas latitud="-175.3343708409366" longitud="-21.070152267610222" altitud="1"/>
                <distancia unidades="m">0</distancia>
                <galeriaFotos>
                    <foto>resort.jpg</foto>
                    <foto>resort.png</foto>
                    <foto>resort.svg</foto>
                    <foto>resort2.jpg</foto>
                    <foto>resort2.png</foto>
                </galeriaFotos>
            </hito>
            <hito nombre="Playa de Ha'atafu">
                <descripcion>Playa protegida para nadar y hacer surf</descripcion>
                <coordenadas latitud="-175.3349976690178" longitud="-21.06976568669056" altitud="1"/>
                <distancia unidades="m">963.99</distancia>
                <galeriaFotos>
                    <foto>playa.png</foto>
                    <foto>playa2.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>cementerio.mp4</video>
                    <video>cementerio.mkv</video>
                    <video>cementerio.avi</video>
                </galeriaVideos>
            </hito>
            <hito nombre="Heilala Holiday Lodge">
                <descripcion>Resort vacacional de Heilala</descripcion>
                <coordenadas latitud="-175.33522905520314" longitud="-21.07158149791907" altitud="1"/>
                <distancia unidades="m">733.22</distancia>
                <galeriaFotos>
                    <foto>cementerio.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>cementerio.mp4</video>
                </galeriaVideos>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Visita Isla Nukunukumotu" tipo="Senderismo" medio="A pie">
        <fecha>19-12-2023</fecha>
        <hora>20:00</hora>
        <tiempo>20 horas</tiempo>
        <agencia>Nukunukumotu Tours</agencia>
        <descripcion>Una visita guiada a la isla de Nukunukumotu</descripcion>
        <personas>Se pueden llevar niños</personas>
        <lugar>Palacio Real de Tonga</lugar>
        <direccion>VQ9X+FQ2, Vuna Rd, Nuku'alofa, Tonga</direccion>
        <coordenadas latitud="-175.2005886457105" longitud="-21.13117063262022" altitud="1"/>
        <referencias>
            <referencia>
                https://www.tripadvisor.es/Attraction_Review-g317040-d315301-Reviews-Ha_atafu_Beach-Tongatapu_Island.html
            </referencia>
            <referencia>
                https://www.surfingtonga.com/index.html
            </referencia>
            <referencia>
                https://www.lonelyplanet.es/oceania/tonga/imprescindible/playa-de-haatafu
            </referencia>
        </referencias>
        <recomendacion valor="10"/>
        <hitos>
            <hito nombre="Ha'atafu Beach Resort">
                <descripcion>Resort cerca de la playa de Ha'atafu (actualmente cerrado)</descripcion>
                <coordenadas latitud="-21.070152267610222" longitud="-175.3343708409366" altitud="1"/>
                <distancia unidades="m">0</distancia>
                <galeriaFotos>
                    <foto>resort.jpg</foto>
                    <foto>resort.png</foto>
                    <foto>resort.svg</foto>
                    <foto>resort2.jpg</foto>
                    <foto>resort2.png</foto>
                </galeriaFotos>
            </hito>
            <hito nombre="Playa de Ha'atafu">
                <descripcion>Playa protegida para nadar y hacer surf</descripcion>
                <coordenadas latitud="-175.3349976690178" longitud="-21.06976568669056" altitud="1"/>
                <distancia unidades="m">963.99</distancia>
                <galeriaFotos>
                    <foto>playa.png</foto>
                    <foto>playa2.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>cementerio.mp4</video>
                    <video>cementerio.mkv</video>
                    <video>cementerio.avi</video>
                </galeriaVideos>
            </hito>
            <hito nombre="Heilala Holiday Lodge">
                <descripcion>Resort vacacional de Heilala</descripcion>
                <coordenadas latitud="-21.07158149791907" longitud="-175.33522905520314" altitud="1"/>
                <distancia unidades="m">733.22</distancia>
                <galeriaFotos>
                    <foto>cementerio.png</foto>
                </galeriaFotos>
                <galeriaVideos>
                    <video>cementerio.mp4</video>
                </galeriaVideos>
            </hito>
        </hitos>
    </ruta>
</rutas>
